# Generated by Django 4.0.2 on 2024-04-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=50)),
                ('filingurl', models.URLField(max_length=2000)),
                ('btc', models.IntegerField()),
                ('btcc', models.CharField(max_length=50)),
                ('btc_source_dt', models.DateField()),
                ('tot_balance_sheet', models.BigIntegerField()),
                ('treasury_type', models.CharField(default='public', max_length=50)),
                ('dateoffirstbuy', models.DateField()),
                ('percentbtc', models.CharField(blank=True, max_length=50, null=True)),
                ('info_url', models.CharField(blank=True, max_length=255, null=True)),
                ('cssclass', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
