# Generated by Django 5.0.4 on 2024-05-29 22:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TreasuriesAPIKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("prefix", models.CharField(editable=False, max_length=8, unique=True)),
                ("hashed_key", models.CharField(editable=False, max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="A free-form name for the API key. Need not be unique. 50 characters max.",
                        max_length=50,
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Once API key expires, clients cannot use it anymore.",
                        null=True,
                        verbose_name="Expires",
                    ),
                ),
                (
                    "hit_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this API key has been used.",
                    ),
                ),
                (
                    "data_used",
                    models.FloatField(
                        default=0, help_text="Amount of data used (in megabytes)."
                    ),
                ),
                (
                    "last_used",
                    models.DateField(
                        default=None,
                        help_text="Date when this API key was last used.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "API key",
                "verbose_name_plural": "API keys",
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Treasury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255, unique=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("exchange", models.CharField(blank=True, max_length=50, null=True)),
                ("symbol", models.CharField(blank=True, max_length=50, null=True)),
                ("filingurl", models.URLField(blank=True, max_length=2000, null=True)),
                ("btc", models.FloatField()),
                ("btc_source_dt", models.DateField()),
                ("treasury_type", models.CharField(default="public", max_length=50)),
                ("dateoffirstbuy", models.DateField(blank=True, null=True)),
                ("info_url", models.CharField(blank=True, max_length=255, null=True)),
                ("cssclass", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Treasury",
                "verbose_name_plural": "Treasuries",
            },
        ),
        migrations.CreateModel(
            name="HistoricalTreasury",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("company", models.CharField(db_index=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("exchange", models.CharField(blank=True, max_length=50, null=True)),
                ("symbol", models.CharField(blank=True, max_length=50, null=True)),
                ("filingurl", models.URLField(blank=True, max_length=2000, null=True)),
                ("btc", models.FloatField()),
                ("btc_source_dt", models.DateField()),
                ("treasury_type", models.CharField(default="public", max_length=50)),
                ("dateoffirstbuy", models.DateField(blank=True, null=True)),
                ("info_url", models.CharField(blank=True, max_length=255, null=True)),
                ("cssclass", models.CharField(blank=True, max_length=50, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Treasury",
                "verbose_name_plural": "historical Treasuries",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
