# Generated by Django 5.0.4 on 2024-04-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasuries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treasury",
            name="company",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
