# Generated by Django 5.0.4 on 2024-04-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("treasuries", "0002_alter_treasury_company"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="treasury",
            unique_together={("exchange", "symbol")},
        ),
    ]
