# Generated by Django 5.0.4 on 2024-04-24 14:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasuries", "0003_alter_treasury_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTreasury",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("company", models.CharField(db_index=True, max_length=255)),
                ("country", models.CharField(max_length=50)),
                ("exchange", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=50)),
                ("filingurl", models.URLField(max_length=2000)),
                ("btc", models.IntegerField()),
                ("btcc", models.CharField(max_length=50)),
                ("btc_source_dt", models.DateField()),
                ("tot_balance_sheet", models.BigIntegerField()),
                ("treasury_type", models.CharField(default="public", max_length=50)),
                ("dateoffirstbuy", models.DateField()),
                ("percentbtc", models.CharField(blank=True, max_length=50, null=True)),
                ("info_url", models.CharField(blank=True, max_length=255, null=True)),
                ("cssclass", models.CharField(blank=True, max_length=50, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical treasury",
                "verbose_name_plural": "historical treasurys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
