# Generated by Django 5.0.4 on 2024-07-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("treasuries", "0003_historicaltreasury_etfshortname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaltreasury",
            old_name="treasury_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="treasury",
            old_name="treasury_type",
            new_name="type",
        ),
    ]
