# Generated by Django 5.0.4 on 2024-04-29 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("treasuries", "0004_historicaltreasury"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaltreasury",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Treasuries",
                "verbose_name_plural": "historical Treasuries",
            },
        ),
        migrations.AlterModelOptions(
            name="treasury",
            options={"verbose_name": "Treasuries", "verbose_name_plural": "Treasuries"},
        ),
    ]
