# Generated by Django 5.0.4 on 2024-07-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasuries", "0004_rename_treasury_type_historicaltreasury_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltreasury",
            name="filingurl",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="info_url",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="filingurl",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="info_url",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
