# Generated by Django 5.0.4 on 2024-05-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasuries', '0006_treasuriesapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltreasury',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Treasury', 'verbose_name_plural': 'historical Treasuries'},
        ),
        migrations.AlterModelOptions(
            name='treasury',
            options={'verbose_name': 'Treasury', 'verbose_name_plural': 'Treasuries'},
        ),
    ]
