# Generated by Django 5.0.4 on 2024-05-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasuries", "0007_alter_historicaltreasury_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltreasury",
            name="btcc",
        ),
        migrations.RemoveField(
            model_name="historicaltreasury",
            name="percentbtc",
        ),
        migrations.RemoveField(
            model_name="historicaltreasury",
            name="tot_balance_sheet",
        ),
        migrations.RemoveField(
            model_name="treasury",
            name="btcc",
        ),
        migrations.RemoveField(
            model_name="treasury",
            name="percentbtc",
        ),
        migrations.RemoveField(
            model_name="treasury",
            name="tot_balance_sheet",
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="country",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="cssclass",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="dateoffirstbuy",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="exchange",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="filingurl",
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="info_url",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="symbol",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="country",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="cssclass",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="dateoffirstbuy",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="exchange",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="filingurl",
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="info_url",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="symbol",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
