# Generated by Django 5.0.4 on 2024-05-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasuries", "0008_remove_historicaltreasury_btcc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltreasury",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="cssclass",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="dateoffirstbuy",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="exchange",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="filingurl",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="info_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="symbol",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="cssclass",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="dateoffirstbuy",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="exchange",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="filingurl",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="info_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="symbol",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
