# Generated by Django 5.0.4 on 2024-05-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasuries", "0009_alter_historicaltreasury_country_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="treasury",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="historicaltreasury",
            name="btc",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="treasury",
            name="btc",
            field=models.FloatField(),
        ),
    ]
